# Generated by Django 4.1.6 on 2023-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='User ID')),
                ('image', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/', verbose_name='Image')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Title')),
                ('article', models.TextField(default='', verbose_name='Article')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('cost', models.FloatField(verbose_name='Cost')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
