# Generated by Django 4.1.6 on 2023-03-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerposts',
            name='user_id',
        ),
        migrations.AddField(
            model_name='providerposts',
            name='providerUser',
            field=models.CharField(default='', max_length=150, verbose_name='User'),
        ),
    ]
