# Generated by Django 4.1.6 on 2023-03-05 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderTitle', models.CharField(default='', max_length=150, verbose_name='Title')),
                ('customerUser', models.CharField(default='', max_length=150, verbose_name='Customer')),
                ('providerUser', models.CharField(default='', max_length=150, verbose_name='Provider')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('orderDate', models.DateTimeField(default=datetime.datetime(2023, 3, 5, 1, 4, 10, 31147), verbose_name='Date')),
                ('orderCategory', models.CharField(default='', max_length=150, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
