# Generated by Django 4.1.6 on 2023-03-05 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_ordersmodel_orderdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersmodel',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='history',
            field=models.BooleanField(default=True, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 9, 19, 28, 126291), verbose_name='Date'),
        ),
    ]
